Assignment3:main
	g++ main.o CashierSystem.o BaristaSystem.o -o Assignment3

main:CashierSystem BaristaSystem
	g++ -std=c++11 -c main.cpp -o main.o

CashierSystem:
	g++ -std=c++11 -c CashierSystem.cpp -o CashierSystem.o

BaristaSystem:
	g++ -std=c++11 -c BaristaSystem.cpp -o BaristaSystem.o